#####################################
# UltraBoomerangs  -  By AbisGamer  #
#####################################

#The armorstand arm position
armorstand:
  x: 0
  y: 120
  z: 0

listener:
  priority: HIGH #Can be HIGH, HIGHEST, LOW, LOWEST, MONITOR, NORMAL

update-old-boomerangs: false # Enable this to update old boomerangs with PDC if you were using 1.0.2 or below, if not then you SHOULD disable it.

boomerangs:
  boomerang_1:
    material: bone #The material
    is-itemstack: false #Material, Name, Lore, custom-model & enchanted are ignored when this is set to true and a valid itemstack is provided
    name: "&6Ultra Boomerang" #The display name
    lore:
      - '&7---'
      - '&6LEGENDARY BOOMERANG'
      - '&7---'
    damage: 50 #Damage done to entities
    custom-model: 1022 #Custom model data
    enchanted: true #Make the boomerang enchanted giving it the glowing effect
    travel-distance: 5 #How far the boomerang should travel when thrown
    click-type: "right" #Possible types: right, left, drop, shift-left or shift-right
    cooldown: 3 #Seconds of cooldown before being able to throw this boomerang again
    mcmmo_skill: "Archery" #if you don't use mcmmo, leave this as none
    mcmmo_skill_amount: 10 #the amount of xp to give
    auraskills_skill: "Archery" #if you don't use mcmmo, leave this as none
    auraskills_skill_amount: 10 #the amount of xp to give
    auto-pickup: true #Auto pickup the loot dropped by the entity killed
    sounds:
      enabled: true
      throw-sound: "ENTITY_ENDER_DRAGON_FLAP"
      receive-sound: "ENTITY_ITEM_PICKUP"
      volume: 1.0
      pitch: 1.0

  boomerang_2:
    is-itemstack: false
    material: iron_axe
    name: "&6Axe Boomerang"
    lore:
      - '&7---'
      - '&6LEGENDARY BOOMERANG'
      - '&7---'
    damage: 90
    custom-model: 1024
    enchanted: false
    travel-distance: 10
    click-type: "right" #Possible types: right, left, drop, shift-left or shift-right
    cooldown: 3 #Seconds of cooldown before being able to throw this boomerang again
    mcmmo_skill: "Archery" #if you don't use mcmmo, leave this as none
    mcmmo_skill_amount: 10 #the amount of xp to give
    auraskills_skill: "Archery" #if you don't use mcmmo, leave this as none
    auraskills_skill_amount: 10 #the amount of xp to give
    auto-pickup: true #Auto pickup the loot dropped by the entity killed
    sounds:
      enabled: true
      throw-sound: "ENTITY_ENDER_DRAGON_FLAP"
      receive-sound: "ENTITY_ITEM_PICKUP"
      volume: 1.0
      pitch: 1.0

  boomerang_3:
    is-itemstack: false
    material: diamond_axe
    name: "&6Chopper Boomerang"
    lore:
      - '&7---'
      - '&6LEGENDARY BOOMERANG'
      - '&7---'
    damage: 150
    custom-model: 1026
    enchanted: true
    travel-distance: 15
    click-type: "left" #Possible types: right, left, drop, shift-left or shift-right
    cooldown: 3 #Seconds of cooldown before being able to throw this boomerang again
    mcmmo_skill: "Archery" #if you don't use mcmmo, leave this as none
    mcmmo_skill_amount: 10 #the amount of xp to give
    auraskills_skill: "Archery" #if you don't use mcmmo, leave this as none
    auraskills_skill_amount: 10 #the amount of xp to give
    auto-pickup: true #Auto pickup the loot dropped by the entity killed
    sounds:
      enabled: true
      throw-sound: "ENTITY_ENDER_DRAGON_FLAP"
      receive-sound: "ENTITY_ITEM_PICKUP"
      volume: 1.0
      pitch: 1.0

  stoney:
    itemstack:
      ==: org.bukkit.inventory.ItemStack
      v: 2230
      type: STONE_SWORD
    is-itemstack: true
    enchanted: true
    damage: 50
    travel-distance: 10
    click-type: "left" #Possible types: right, left, drop, shift-left or shift-right
    cooldown: 3 #Seconds of cooldown before being able to throw this boomerang again
    mcmmo_skill: "Archery" #if you don't use mcmmo, leave this as none
    mcmmo_skill_amount: 10 #the amount of xp to give
    auraskills_skill: "Archery" #if you don't use mcmmo, leave this as none
    auraskills_skill_amount: 10 #the amount of xp to give
    auto-pickup: true #Auto pickup the loot dropped by the entity killed
    sounds:
      enabled: true
      throw-sound: "ENTITY_ENDER_DRAGON_FLAP"
      receive-sound: "ENTITY_ITEM_PICKUP"
      volume: 1.0
      pitch: 1.0

  #This one gets thrown when you drop it, get it, dropper, haha? no funny? okay
  dropper:
    itemstack:
      ==: org.bukkit.inventory.ItemStack
      v: 2230
      type: DROPPER
    is-itemstack: true
    damage: 50
    travel-distance: 10
    click-type: "drop" #Possible types: right, left, drop, shift-left or shift-right
    cooldown: 3 #Seconds of cooldown before being able to throw this boomerang again
    mcmmo_skill: "Archery" #if you don't use mcmmo, leave this as none
    mcmmo_skill_amount: 10 #the amount of xp to give
    auraskills_skill: "Archery" #if you don't use mcmmo, leave this as none
    auraskills_skill_amount: 10 #the amount of xp to give
    auto-pickup: true #Auto pickup the loot dropped by the entity killed
    sounds:
      enabled: true
      throw-sound: "ENTITY_ENDER_DRAGON_FLAP"
      receive-sound: "ENTITY_ITEM_PICKUP"
      volume: 1.0
      pitch: 1.0
