#####################################
# UltraBoomerangs  -  By AbisGamer  #
#####################################

#The armorstand arm position
armorstand:
  x: 0
  y: 120
  z: 0

listener:
  priority: HIGH #Can be HIGH, HIGHEST, LOW, LOWEST, MONITOR, NORMAL

boomerangs:
  boomerang_1:
    material: bone #The material
    is-itemstack: false #Material, Name, Lore, custom-model & enchanted are ignored when this is set to true and a valid itemstack is provided
    name: "&6Ultra Boomerang" #The display name
    lore:
      - '&7---'
      - '&6LEGENDARY BOOMERANG'
      - '&7---'
    damage: 50 #Damage done to entities
    custom-model: 1022 #Custom model data
    enchanted: true #Make the boomerang enchanted giving it the glowing effect
    travel-distance: 5 #How far the boomerang should tavel when thrown
    click-type: "right" #Possible types: right & left
    cooldown: 3 #Seconds of cooldown before being able to throw this boomerang again

  boomerang_2:
    is-itemstack: false
    material: iron_axe
    name: "&6Axe Boomerang"
    lore:
      - '&7---'
      - '&6LEGENDARY BOOMERANG'
      - '&7---'
    damage: 90
    custom-model: 1024
    enchanted: false
    travel-distance: 10
    click-type: "right"
    cooldown: 3 #Seconds of cooldown before being able to throw this boomerang again

  boomerang_3:
    is-itemstack: false
    material: diamond_axe
    name: "&6Chopper Boomerang"
    lore:
      - '&7---'
      - '&6LEGENDARY BOOMERANG'
      - '&7---'
    damage: 150
    custom-model: 1026
    enchanted: true
    travel-distance: 15
    right-click: true
    click-type: "left"
    cooldown: 3 #Seconds of cooldown before being able to throw this boomerang again


  stoney:
    itemstack:
      ==: org.bukkit.inventory.ItemStack
      v: 3578
      type: STONE_SWORD
    is-itemstack: true
    damage: 50
    travel-distance: 10
    click-type: "left"
    cooldown: 3 #Seconds of cooldown before being able to throw this boomerang again